### ISSUE TITLE
Покрытие в процентах всего датасета каждым ассесором

### ISSUE THREAD

**Issue by Zheka001** [RomanSteinberg/mass-labeling#4]
Сейчас на странице статистика видна следующая картина
![image](https://user-images.githubusercontent.com/32735813/123221834-03666a00-d4d8-11eb-9c05-14bb87ec7520.png)

Хочется рядом со статистикой просмотров видеть покрытие в процентах всего датасета или в абсолютной форме: 

Оценил 75 % (150/200)

**Comment by solidovic** [comment]
вывел всего тасков в датасете

**Comment by Zheka001** [comment]
Принято.
