### ISSUE TITLE
Проверить, что при сохранении анкеты в нее не добавляются пустые элементы в списке

### ISSUE THREAD

**Issue by Zheka001** [RomanSteinberg/mass-labeling#5]
![image](https://user-images.githubusercontent.com/32735813/123806202-62244d00-d8f7-11eb-98e2-68e7294af88f.png)
Плохой пример того, как они добавляются пустыми.

**Comment by solidovic** [comment]
сделал при сохранение проверку пустых полей, если они есть - то форма не добавится и выведется уведомление

**Comment by solidovic** [comment]
прошу проверить

**Comment by Zheka001** [comment]
При появлении уведомления "Форма невалидная" не очень понятно, чего именно не хватает. Нельзя ли подсвечивать красным цветом незаполненные поля? Либо сделать так, чтобы пустыми не могли оставаться только поля с неограниченным количество добавлений - те, на которых есть кнопка добавить/удалить.

Опишу подробней, что раздражает заказчика: разметчик заполнял образование, заполнил одно, второе и случайно жмакнул на 3, при этом оставил его пустым. В режиме оценивания он увидит два образования и пустое поле, которое будет просто поедать место на экране. Хочется этого избежать.

**Comment by Zheka001** [comment]
Все работает, отлично!)
