### ISSUE TITLE
Выводить уведомление об успешном сохранении анкеты

### ISSUE THREAD

**Issue by Zheka001** [RomanSteinberg/mass-labeling#7]
В режиме добавления новых данных для анкет необходимо выводить уведомление об успешно сохраненной анкете.

**Comment by solidovic** [comment]
прошу проверить

**Comment by Zheka001** [comment]
Уведомление не выводится, просто обнуляются данные.

**Comment by Zheka001** [comment]
Уведомление выводилось для режима оценивания. Уже выводится и в режиме занесения анкет. Все работает, спасибо!
